"""Migration 

Revision ID: bce8e5d9ebc1
Revises: cd455df7e721
Create Date: 2022-06-15 20:38:08.426676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bce8e5d9ebc1'
down_revision = 'cd455df7e721'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
