# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ms_storage/protos/crawler.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fms_storage/protos/crawler.proto\x12\x07\x63rawler\x1a\x1cgoogle/protobuf/struct.proto\" \n\x0e\x43ookiesRequest\x12\x0e\n\x06market\x18\x01 \x01(\t\";\n\x0f\x43ookiesResponse\x12(\n\x07\x63ookies\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"\x1d\n\rMarketRequest\x12\x0c\n\x04stub\x18\x01 \x01(\t\" \n\x0eMarketResponse\x12\x0e\n\x06market\x18\x01 \x01(\t2\x90\x01\n\x07\x43rawler\x12\x41\n\nGetCookies\x12\x17.crawler.CookiesRequest\x1a\x18.crawler.CookiesResponse\"\x00\x12\x42\n\rWaitForMarket\x12\x16.crawler.MarketRequest\x1a\x17.crawler.MarketResponse\"\x00\x62\x06proto3')



_COOKIESREQUEST = DESCRIPTOR.message_types_by_name['CookiesRequest']
_COOKIESRESPONSE = DESCRIPTOR.message_types_by_name['CookiesResponse']
_MARKETREQUEST = DESCRIPTOR.message_types_by_name['MarketRequest']
_MARKETRESPONSE = DESCRIPTOR.message_types_by_name['MarketResponse']
CookiesRequest = _reflection.GeneratedProtocolMessageType('CookiesRequest', (_message.Message,), {
  'DESCRIPTOR' : _COOKIESREQUEST,
  '__module__' : 'ms_storage.protos.crawler_pb2'
  # @@protoc_insertion_point(class_scope:crawler.CookiesRequest)
  })
_sym_db.RegisterMessage(CookiesRequest)

CookiesResponse = _reflection.GeneratedProtocolMessageType('CookiesResponse', (_message.Message,), {
  'DESCRIPTOR' : _COOKIESRESPONSE,
  '__module__' : 'ms_storage.protos.crawler_pb2'
  # @@protoc_insertion_point(class_scope:crawler.CookiesResponse)
  })
_sym_db.RegisterMessage(CookiesResponse)

MarketRequest = _reflection.GeneratedProtocolMessageType('MarketRequest', (_message.Message,), {
  'DESCRIPTOR' : _MARKETREQUEST,
  '__module__' : 'ms_storage.protos.crawler_pb2'
  # @@protoc_insertion_point(class_scope:crawler.MarketRequest)
  })
_sym_db.RegisterMessage(MarketRequest)

MarketResponse = _reflection.GeneratedProtocolMessageType('MarketResponse', (_message.Message,), {
  'DESCRIPTOR' : _MARKETRESPONSE,
  '__module__' : 'ms_storage.protos.crawler_pb2'
  # @@protoc_insertion_point(class_scope:crawler.MarketResponse)
  })
_sym_db.RegisterMessage(MarketResponse)

_CRAWLER = DESCRIPTOR.services_by_name['Crawler']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COOKIESREQUEST._serialized_start=74
  _COOKIESREQUEST._serialized_end=106
  _COOKIESRESPONSE._serialized_start=108
  _COOKIESRESPONSE._serialized_end=167
  _MARKETREQUEST._serialized_start=169
  _MARKETREQUEST._serialized_end=198
  _MARKETRESPONSE._serialized_start=200
  _MARKETRESPONSE._serialized_end=232
  _CRAWLER._serialized_start=235
  _CRAWLER._serialized_end=379
# @@protoc_insertion_point(module_scope)
