# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ms_storage/protos/scraper.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fms_storage/protos/scraper.proto\x12\x07scraper\x1a\x1cgoogle/protobuf/struct.proto\"<\n\rScrapeRequest\x12\x0e\n\x06market\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\":\n\x0eScrapeResponse\x12(\n\x07\x63ontent\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct2F\n\x07Scraper\x12;\n\x06Scrape\x12\x16.scraper.ScrapeRequest\x1a\x17.scraper.ScrapeResponse\"\x00\x62\x06proto3')



_SCRAPEREQUEST = DESCRIPTOR.message_types_by_name['ScrapeRequest']
_SCRAPERESPONSE = DESCRIPTOR.message_types_by_name['ScrapeResponse']
ScrapeRequest = _reflection.GeneratedProtocolMessageType('ScrapeRequest', (_message.Message,), {
  'DESCRIPTOR' : _SCRAPEREQUEST,
  '__module__' : 'ms_storage.protos.scraper_pb2'
  # @@protoc_insertion_point(class_scope:scraper.ScrapeRequest)
  })
_sym_db.RegisterMessage(ScrapeRequest)

ScrapeResponse = _reflection.GeneratedProtocolMessageType('ScrapeResponse', (_message.Message,), {
  'DESCRIPTOR' : _SCRAPERESPONSE,
  '__module__' : 'ms_storage.protos.scraper_pb2'
  # @@protoc_insertion_point(class_scope:scraper.ScrapeResponse)
  })
_sym_db.RegisterMessage(ScrapeResponse)

_SCRAPER = DESCRIPTOR.services_by_name['Scraper']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCRAPEREQUEST._serialized_start=74
  _SCRAPEREQUEST._serialized_end=134
  _SCRAPERESPONSE._serialized_start=136
  _SCRAPERESPONSE._serialized_end=194
  _SCRAPER._serialized_start=196
  _SCRAPER._serialized_end=266
# @@protoc_insertion_point(module_scope)
