# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ms_crawler.protos import planner_pb2 as ms__crawler_dot_protos_dot_planner__pb2


class PlannerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPlan = channel.unary_unary(
                '/planner.Planner/GetPlan',
                request_serializer=ms__crawler_dot_protos_dot_planner__pb2.PlanRequest.SerializeToString,
                response_deserializer=ms__crawler_dot_protos_dot_planner__pb2.PlanResponse.FromString,
                )


class PlannerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlannerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlan,
                    request_deserializer=ms__crawler_dot_protos_dot_planner__pb2.PlanRequest.FromString,
                    response_serializer=ms__crawler_dot_protos_dot_planner__pb2.PlanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'planner.Planner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Planner(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/planner.Planner/GetPlan',
            ms__crawler_dot_protos_dot_planner__pb2.PlanRequest.SerializeToString,
            ms__crawler_dot_protos_dot_planner__pb2.PlanResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
