# Copyright 2023 Ricardo Yaben
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ms_crawler/protos/planner.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fms_crawler/protos/planner.proto\x12\x07planner\x1a\x1cgoogle/protobuf/struct.proto\"\x1d\n\x0bPlanRequest\x12\x0e\n\x06market\x18\x01 \x01(\t\"5\n\x0cPlanResponse\x12%\n\x04plan\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct2C\n\x07Planner\x12\x38\n\x07GetPlan\x12\x14.planner.PlanRequest\x1a\x15.planner.PlanResponse\"\x00\x62\x06proto3')



_PLANREQUEST = DESCRIPTOR.message_types_by_name['PlanRequest']
_PLANRESPONSE = DESCRIPTOR.message_types_by_name['PlanResponse']
PlanRequest = _reflection.GeneratedProtocolMessageType('PlanRequest', (_message.Message,), {
  'DESCRIPTOR' : _PLANREQUEST,
  '__module__' : 'ms_crawler.protos.planner_pb2'
  # @@protoc_insertion_point(class_scope:planner.PlanRequest)
  })
_sym_db.RegisterMessage(PlanRequest)

PlanResponse = _reflection.GeneratedProtocolMessageType('PlanResponse', (_message.Message,), {
  'DESCRIPTOR' : _PLANRESPONSE,
  '__module__' : 'ms_crawler.protos.planner_pb2'
  # @@protoc_insertion_point(class_scope:planner.PlanResponse)
  })
_sym_db.RegisterMessage(PlanResponse)

_PLANNER = DESCRIPTOR.services_by_name['Planner']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLANREQUEST._serialized_start=74
  _PLANREQUEST._serialized_end=103
  _PLANRESPONSE._serialized_start=105
  _PLANRESPONSE._serialized_end=158
  _PLANNER._serialized_start=160
  _PLANNER._serialized_end=227
# @@protoc_insertion_point(module_scope)
