# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lib/src/lib/protos/crawler.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n lib/src/lib/protos/crawler.proto\x12\x07\x63rawler\x1a\x1cgoogle/protobuf/struct.proto\" \n\x0e\x43ookiesRequest\x12\x0e\n\x06market\x18\x01 \x01(\t\";\n\x0f\x43ookiesResponse\x12(\n\x07\x63ookies\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"\x1d\n\rMarketRequest\x12\x0c\n\x04stub\x18\x01 \x01(\t\" \n\x0eMarketResponse\x12\x0e\n\x06market\x18\x01 \x01(\t2\x90\x01\n\x07\x43rawler\x12\x41\n\nGetCookies\x12\x17.crawler.CookiesRequest\x1a\x18.crawler.CookiesResponse\"\x00\x12\x42\n\rWaitForMarket\x12\x16.crawler.MarketRequest\x1a\x17.crawler.MarketResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lib.src.lib.protos.crawler_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_COOKIESREQUEST']._serialized_start=75
  _globals['_COOKIESREQUEST']._serialized_end=107
  _globals['_COOKIESRESPONSE']._serialized_start=109
  _globals['_COOKIESRESPONSE']._serialized_end=168
  _globals['_MARKETREQUEST']._serialized_start=170
  _globals['_MARKETREQUEST']._serialized_end=199
  _globals['_MARKETRESPONSE']._serialized_start=201
  _globals['_MARKETRESPONSE']._serialized_end=233
  _globals['_CRAWLER']._serialized_start=236
  _globals['_CRAWLER']._serialized_end=380
# @@protoc_insertion_point(module_scope)
