# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lib/src/lib/protos/scraper.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n lib/src/lib/protos/scraper.proto\x12\x07scraper\x1a\x1cgoogle/protobuf/struct.proto\"<\n\rScrapeRequest\x12\x0e\n\x06market\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\":\n\x0eScrapeResponse\x12(\n\x07\x63ontent\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct2F\n\x07Scraper\x12;\n\x06Scrape\x12\x16.scraper.ScrapeRequest\x1a\x17.scraper.ScrapeResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lib.src.lib.protos.scraper_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SCRAPEREQUEST']._serialized_start=75
  _globals['_SCRAPEREQUEST']._serialized_end=135
  _globals['_SCRAPERESPONSE']._serialized_start=137
  _globals['_SCRAPERESPONSE']._serialized_end=195
  _globals['_SCRAPER']._serialized_start=197
  _globals['_SCRAPER']._serialized_end=267
# @@protoc_insertion_point(module_scope)
