defaults:
  - base_config
  - host: crawler
  - clients:
    - storage
    - core
    - planner
  - _self_ 

resources: dist

hydra:
  searchpath:
    - file://config
  output_subdir: null  
  run:  
    dir: .